### ISSUE TITLE
(Micro-)nutrient contents

### ISSUE THREAD

**Issue by egbendito** [reagro/terminag#2]
Looking at the micro and macro nutrients in [soil](https://github.com/reagro/terminag/blob/main/variables/variables_soil.csv) and [crop](https://github.com/reagro/terminag/blob/main/variables/variables_crop.csv) vocabularies seem to have some limited ranges. Particularly for nitrogen (N) these are in the lower range (1000 mg/kg) of what I have seen in some literature... See a couple links:

1. [https://doi.org/10.1016/j.heliyon.2023.e17321](https://doi.org/10.1016/j.heliyon.2023.e17321)
2. [https://doi.org/10.3390/rs12071139](https://doi.org/10.3390/rs12071139)

This is probably a compromise for different crops, which probably have different ranges of (micro-) nutrients and the check will happen across all crops. Perhaps the ranges for the different parts (grain, leaf, etc) could also be moved to the [crops](https://github.com/reagro/terminag/blob/main/values/values_crop.csv) specific vocabulary (same as for `yield`)?

@rhijmans @celineaubert @cedricngakou

**Comment by rhijmans** [comment]
They are sanity checks for the order of magnitude. If they are too low, they can be increased. Setting limits by crop would be too cumbersome.
